### ISSUE TITLE
Consume retries on the same node despite of getting multiple truncation errors

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#577]
When working with STP, it gets consume truncation from some node in source env. Then consume retries to the same node despite of having multiple truncation errors. It should be switched to another node or the solution should be on the server side

**Comment by hochgi** [comment]
Also, retrying to same ws has higher chances of success, due to caching...

If ES is stressed, you'll get truncations on every ws.

**Comment by YoniMataraso** [comment]
Will be handled as part of the streams improvements #436

**Comment by nicklester** [comment]
@yanpom - is this still a valid enhancement. The actual issue is not an STP issue and is related to streams improvement #436. I think @hochgi suggested that the current mode of operation (same ws) has a higher chance of success, so maybe we need to leave as is, close ticket and await streams improvement?

**Comment by nicklester** [comment]
@yanpom - can you address above comment?

**Comment by nicklester** [comment]
@yanpom requested to close as the configurable retries have addressed this issue
